# CMake generated Testfile for 
# Source directory: /home/pi/picreate/Create2/ws/src/ros_comm/rostopic
# Build directory: /home/pi/picreate/Create2/ws/build_isolated/rostopic
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rostopic_rostest_test_rostopic.test "/home/pi/picreate/Create2/ws/build_isolated/rostopic/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/picreate/Create2/ws/build_isolated/rostopic/test_results/rostopic/rostest-test_rostopic.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/picreate/Create2/ws/src/ros_comm/rostopic --package=rostopic --results-filename test_rostopic.xml --results-base-dir \"/home/pi/picreate/Create2/ws/build_isolated/rostopic/test_results\" /home/pi/picreate/Create2/ws/src/ros_comm/rostopic/test/rostopic.test ")
set_tests_properties(_ctest_rostopic_rostest_test_rostopic.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/pi/picreate/Create2/ws/src/ros_comm/rostopic/CMakeLists.txt;13;add_rostest;/home/pi/picreate/Create2/ws/src/ros_comm/rostopic/CMakeLists.txt;0;")
add_test(_ctest_rostopic_nosetests_test.test_rostopic_command_line_offline.py "/home/pi/picreate/Create2/ws/build_isolated/rostopic/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/picreate/Create2/ws/build_isolated/rostopic/test_results/rostopic/nosetests-test.test_rostopic_command_line_offline.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/pi/picreate/Create2/ws/build_isolated/rostopic/test_results/rostopic" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/pi/picreate/Create2/ws/src/ros_comm/rostopic/test/test_rostopic_command_line_offline.py --with-xunit --xunit-file=/home/pi/picreate/Create2/ws/build_isolated/rostopic/test_results/rostopic/nosetests-test.test_rostopic_command_line_offline.py.xml")
set_tests_properties(_ctest_rostopic_nosetests_test.test_rostopic_command_line_offline.py PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/pi/picreate/Create2/ws/src/ros_comm/rostopic/CMakeLists.txt;15;catkin_add_nosetests;/home/pi/picreate/Create2/ws/src/ros_comm/rostopic/CMakeLists.txt;0;")
subdirs("gtest")
